{
 "title": "1. PowerScale Cluster Overview",
 "description": "Initial dashboard to provide a quick overview of how the cluster is working.",
 "tags": [
  "isilon",
  "idi-v1",
  "PowerScale"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "nfs,nfs3,nfs4,cifs,smb,smb1,smb2,hdfs,ftp,siq,lsass_in,lsass_out,"
   }
  ]
 },
 "panels": [
  { "title": "Intro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Introduction",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1>Welcome to the PowerScale Data Insights.</h1> \n\nThis tool was designed to give customer and Dell UDS Presales a simple easy way to collect and share relevant telemetry information from OneFS Clusters. Feel free to integrate with other Grafana dashbaords and data sources to create application based mash-ups and provide a deeper <b>insight</b>.<br>\n<br>On this dashboard you will find relevant cluster wide statistics that can give a quick glimpse as to what is happening across a broad set of metrics.\nIt can be used to identify and drill down on time ranges of interest. \nUse these time ranges on other dashbaords to further analysis.\n<br>\n<h3>Usage Notes</h3>\nUse the cluster and other pull downs to select the cluster and protocol(s) of interest.  A seperate chart will be displayed for each protocol chosen.\n<br>Use highlight with your mouse the time period you want to zoom into or use the pull downs at the top right to select specific time periods.\n<br>Note that by default the dates and time displayed are in your browser’s time zone, not the source cluster.   You can get it to display in UTC via the settings under the little gear symbol at the top of the page.\n<br>If there is a legend displayed you can click on elements within it to hide or display items, etc.\n<br>Click on the title of the chart and then the horizontal bars icon at the left to show/hide the legend and get a CSV export of the data.\n<br>The charts are displayed to connect the data points and the null values so drop-outs will look weird.\n"
   }
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Avg. Network Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Reads",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.out.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Max $proto Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "HDFS Reads",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.protostats.hdfs.total",
     "query": "SELECT max(\"out_rate\") FROM \"cluster.protostats.$proto.total\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "out_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Avg. Network Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Writes",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.in.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Max $proto Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "HDFS Reads",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.protostats.hdfs.total",
     "query": "SELECT max(\"in_rate\") FROM \"cluster.protostats.$proto.total\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "out_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cluster CPU Breakdown - $cluster",
   "type": "timeseries",
   "description": "This is the CPU contributions from OneFS.  It is a stacked chart and the totals will be measured along with the contribution from each piece.  Use the hover tooltip to get exact values along the chart.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "intr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.cpu.intr.avg",
     "query": "SELECT mean(\"value\")  / 100 FROM \"cluster.cpu.user.avg\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "sys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.cpu.sys.avg",
     "query": "SELECT mean(\"value\")  / 100 FROM \"cluster.cpu.user.avg\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.cpu.user.avg",
     "query": "SELECT mean(\"value\")  / 100 FROM \"cluster.cpu.user.avg\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.heat.getattr.total",
     "query": "SELECT mean(\"value\") FROM /node.ifs.heat.(.*).total/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Filesystem Heat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Max lsass_out Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_op_name ($tag_class_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "op_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.protostats.lsass_out",
     "query": "SELECT mean(\"time_avg\")  / 1000 FROM \"cluster.protostats.$protocol\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval), \"class_name\",  \"op_name\" fill(null)",
     "select": [
      [
       { "params": [ "time_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Total File Operations & Capacity Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Total /ifs Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_cluster Writes",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.ops.in.rate",
     "metric": "dfs.namenode.TotalFileOps",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "$tag_cluster Reads",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.ops.out.rate",
     "metric": "dfs.namenode.TotalFileOps",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Capacity Cluster Wide",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Bytes Used",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.bytes.used",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "Bytes Available",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.bytes.total",
     "metric": "dfs.FSNamesystem.CapacityTotalGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Cluster Data Reduction - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Compression Ratio",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.compression.ratio",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "Dedupe Ratio",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.dedupe.inline.ratio",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  { "title": "L1 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "L1 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 67 },
   "options": {
    "content": "# L1 Cache\nOr Level 1 cache is a client side cache that caches file objects as they are accessed on that particular node."
   }
  },
  {
   "title": "L1 Prefetch Cache - $cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_prefetch_hit\") /max(\"l2_data_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_prefetch_hit\") /max(\"l2_meta_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "L1 Cache - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L1 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_data_read_hit\") /max(\"l1_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L1 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_meta_read_hit\") /max(\"l1_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L2 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "L2 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 75 },
   "options": {
    "content": "# L2 Cache\nLevel 2 cache is a back-end cache that caches file block that reside on that particular node."
   }
  },
  {
   "title": "L2 Prefetch Cache - $cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L3 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_prefetch_hit\") /max(\"l2_data_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L3 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_prefetch_hit\") /max(\"l2_meta_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.cache",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_read_hit\") /max(\"l2_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "L2 Cache - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_read_hit\") /max(\"l2_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_read_hit\") /max(\"l2_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L3 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "L3 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 83 },
   "options": {
    "content": "# L3 Cache\nLevel 3 cache is an SSD backed cache that works with L2 Cache and contains blocks and metadata that are local to that particular node."
   }
  },
  {
   "title": "L3 Cache - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L3 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l3_data_read_hit\") /max(\"l3_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L3 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l3_meta_read_hit\") /max(\"l3_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Disk IO for $cluster",
   "type": "timeseries",
   "description": "THis is a stacked graph so the total R+W is plotted for the overall B/W.  At the same time showing the contributions from each.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.disk.bytes.in.rate",
     "precision": "default",
     "query": "SELECT mean(\"value\") FROM \"cluster.disk.bytes.in.rate\" WHERE (\"cluster\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.disk.bytes.out.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "External Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}