{
 "title": "3. PowerScale Node Summary",
 "description": "This dashboard provides the metrics that are particular to a node.",
 "tags": [
  "isilon",
  "PowerScale"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "node",
    "label": "Nodes",
    "query": "show tag values with key = \"node\" where \"cluster\" =~ /^$cluster/"
   }
  ]
 },
 "panels": [
  { "title": "CPU Subsystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node $node Max CPU: sys",
   "type": "stat",
   "description": "Maximum value of sys during the interval",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.cpu.sys.max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Node $node CPU Utilization",
   "type": "timeseries",
   "description": "Collection of the CPU based stats",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.cpu.idle.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "intr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.cpu.intr.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.cpu.nice.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "sys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.cpu.sys.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.cpu.user.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "Disk Subsystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "description": "Average bytes read per second for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.bytes.out.rate.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.bytes.in.rate.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Scheduler Latency",
   "type": "timeseries",
   "description": "Avg iosched latency for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.iosched.latency.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "description": "Average access latency for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.access.latency.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Scheduler Queue Length",
   "type": "timeseries",
   "description": "Avg iosched queue length for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.iosched.queue.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Busy",
   "type": "timeseries",
   "description": "Average disk busy percent, per node.  The graph stacks the node contribbutions at 100% per node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.busy.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "External Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "External Network Incoming Throughput",
   "type": "timeseries",
   "description": "This is a \"Stacked\" chart and the scale is the aggregate of all nodes displayed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.bytes.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "External Network Outgoing Throughput",
   "type": "timeseries",
   "description": "This is a \"Stacked\" chart and the scale is the aggregate of all nodes displayed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.bytes.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "Internal Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Internal Network Incoming Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.bytes.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Network Outgoing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.bytes.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "Network Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "External Network Errors",
   "type": "graph",
   "description": "Incoming errors per second for a node's external interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Incoming node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.errors.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Outgoing node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.errors.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Network Errors",
   "type": "timeseries",
   "description": "Errors per second for a node's internal interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Incoming node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.errors.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Outgoing node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.errors.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}