{
 "title": "3. PowerScale Node Summary",
 "description": "This dashboard provides the metrics that are particular to a node.",
 "tags": [
  "isilon",
  "idi-v1",
  "PowerScale"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "node",
    "label": "Nodes",
    "query": "show tag values with key = \"node\" where \"cluster\" =~ /^$cluster/"
   }
  ]
 },
 "panels": [
  { "title": "Disk Subsystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Reads",
   "type": "graph",
   "description": "Average bytes read per second for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.bytes.out.rate.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.bytes.in.rate.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Scheduler Latency",
   "type": "graph",
   "description": "Avg iosched latency for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.iosched.latency.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "Average access latency for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.access.latency.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Scheduler Queue Length",
   "type": "graph",
   "description": "Avg iosched queue length for all disks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.iosched.queue.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Busy",
   "type": "graph",
   "description": "Average disk busy percent, per node.  The graph stacks the node contribbutions at 100% per node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.disk.busy.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "External Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "External Network Incoming Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.bytes.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "External Network Outgoing Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.bytes.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "Internal Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Internal Network Incoming Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.bytes.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Network Outgoing Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.bytes.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "Network Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "External Network Errors",
   "type": "graph",
   "description": "Incoming errors per second for a node's external interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Incoming node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.errors.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Outgoing node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.errors.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Network Errors",
   "type": "timeseries",
   "description": "Errors per second for a node's internal interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Incoming node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.errors.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Outgoing node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.int.errors.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}