{
 "title": "PowerScale Cache Analysis (Beta)",
 "tags": [
  "isilon",
  "powerscale",
  "pk"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "node",
    "label": "Node",
    "query": "select node  from (select last(l1_data_read_hit) from \"node.ifs.cache\"  where $timeFilter and \"cluster\" =~ /$cluster/ group by \"cluster\", \"node\") where \"cluster\" =~/$cluster/"
   }
  ]
 },
 "panels": [
  { "title": "PowerScale Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L1 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "# L1 Cache\nOr Level 1 cache is a client side cache that caches file objects as they are accessed on that particular node."
   }
  },
  {
   "title": "L2 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 1 },
   "options": {
    "content": "# L2 Cache\nLevel 2 cache is a back-end cache that caches file block that reside on that particular node."
   }
  },
  {
   "title": "L3 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": {
    "content": "# L3 Cache\nLevel 3 cache is an SSD backed cache that works with L2 Cache and contains blocks and metadata that are local to that particular node."
   }
  },
  { "title": "Heads-Up Prefetch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "L1 Prefetch Cache - $cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L1 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_data_prefetch_hit\") /max(\"l1_data_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"l1_data_prefetch_hit\" > 0 and $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L1 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_meta_prefetch_hit\") /max(\"l1_meta_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"l1_data_prefetch_hit\" >0 and $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "L2 Prefetch Cache - $cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_prefetch_hit\") /max(\"l2_data_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter and \"l2_data_prefetch_hit\" > 0 GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_prefetch_hit\") /max(\"l2_meta_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter and \"l2_meta_prefetch_hit\" >0 GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L1 Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "L1 Cache - Node $node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L1 Data $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l1_data_read_hit\") /mean(\"l1_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ and $timeFilter GROUP BY \"node\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L1 Metadata $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l1_meta_read_hit\") /mean(\"l1_meta_read_start\") FROM \"node.ifs.cache\" WHERE ( \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ )  and $timeFilter GROUP BY \"node\",  time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L2 Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "L2 Cache - Node $node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Data - Node $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l2_data_read_hit\") /mean(\"l2_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ and \"l2_data_read_hit\" > 0 and $timeFilter GROUP BY \"node\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata - Node $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l2_meta_read_hit\") /mean(\"l2_meta_read_start\") FROM \"node.ifs.cache\" WHERE ( \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ ) and \"l2_meta_read_hit\" > 0 and  $timeFilter GROUP BY \"node\",  time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "L2 Prefetch - Node $node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Data Prefetch - Node $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l2_data_prefetch_hit\") /mean(\"l2_data_prefetch_start\") FROM \"node.ifs.cache\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ ) and $timeFilter GROUP BY  time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata Prefetch - Node $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l2_meta_prefetch_hit\") /mean(\"l2_meta_prefetch_start\") FROM \"node.ifs.cache\" WHERE ( \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ ) and  $timeFilter GROUP BY  time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L3 Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "L3 Cache - Node $node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L3 Data Read - Node $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l3_data_read_hit\") /mean(\"l3_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ and \"l3_data_read_hit\" > 0 and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L3 Metadata Read - Node $node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT mean(\"l3_meta_read_hit\") /mean(\"l3_meta_read_start\") FROM \"node.ifs.cache\" WHERE ( \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ ) and \"l3_meta_read_hit\" >0 and  $timeFilter GROUP BY  time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "L2 vs. L3 - Node $node",
   "type": "timeseries",
   "description": "This is the relative cache throughput.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L3 Data Read - Node $node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.cache",
     "precision": "default",
     "query": "SELECT mean(\"l3_data_read_hit\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ and $timeFilter GROUP BY \"node\",fill(null)",
     "select": [
      [
       { "params": [ "l3_data_read_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Data Read - Node $node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.cache",
     "precision": "default",
     "query": "SELECT mean(\"l2_data_read_hit\") FROM \"node.ifs.cache\" WHERE ( \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ ) and \n $timeFilter GROUP BY \"node\",  time($interval) fill(null)",
     "select": [
      [
       { "params": [ "l2_data_read_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Net Reads - Node $node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.net.ext.bytes.out.rate",
     "precision": "default",
     "query": "SELECT mean(\"l2_data_read_hit\") FROM \"node.ifs.cache\" WHERE ( \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ ) and \n $timeFilter GROUP BY \"node\",  time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  }
 ]
}