{
 "title": "PowerScale Cluster Overview",
 "description": "Initial dashboard to provide a quick overview of how the cluster is working.",
 "tags": [
  "isilon",
  "pk"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "nfs,nfs3,nfs4,cifs,smb,smb1,smb2,hdfs,ftp,siq,lsass_in,lsass_out,"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. Network Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Reads",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.out.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Max $proto Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "HDFS Reads",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.protostats.hdfs.total",
     "query": "SELECT max(\"out_rate\") FROM \"cluster.protostats.$proto.total\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "out_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Avg. Network Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Writes",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.in.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Max $proto Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "HDFS Reads",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.protostats.hdfs.total",
     "query": "SELECT max(\"in_rate\") FROM \"cluster.protostats.$proto.total\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "out_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cluster CPU Breakdown - $cluster",
   "type": "timeseries",
   "description": "This is the CPU contributions from OneFS.  It is a stacked chart and the totals will be measured along with the contribution from each piece.  Use the hover tooltip to get exact values along the chart.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "intr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.cpu.intr.avg",
     "query": "SELECT mean(\"value\")  / 100 FROM \"cluster.cpu.user.avg\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "sys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.cpu.sys.avg",
     "query": "SELECT mean(\"value\")  / 100 FROM \"cluster.cpu.user.avg\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.cpu.user.avg",
     "query": "SELECT mean(\"value\")  / 100 FROM \"cluster.cpu.user.avg\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  { "title": "Filesystem Heat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.heat.getattr.total",
     "query": "SELECT mean(\"value\") FROM /node.ifs.heat.(.*).total/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max lsass_out Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_op_name ($tag_class_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "op_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.protostats.lsass_out",
     "query": "SELECT mean(\"time_avg\")  / 1000 FROM \"cluster.protostats.$protocol\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval), \"class_name\",  \"op_name\" fill(null)",
     "select": [
      [
       { "params": [ "time_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Total File Operations & Capacity Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Total /ifs Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_cluster Writes",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.ops.in.rate",
     "metric": "dfs.namenode.TotalFileOps",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "$tag_cluster Reads",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.ops.out.rate",
     "metric": "dfs.namenode.TotalFileOps",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Capacity Cluster Wide",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Bytes Used",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.bytes.used",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "Bytes Available",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.bytes.total",
     "metric": "dfs.FSNamesystem.CapacityTotalGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Cluster Data Reduction - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Compression Ratio",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.compression.ratio",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "Dedupe Ratio",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster.dedupe.inline.ratio",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  { "title": "L1 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "L1 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 68 },
   "options": {
    "content": "# L1 Cache\nOr Level 1 cache is a client side cache that caches file objects as they are accessed on that particular node."
   }
  },
  {
   "title": "L1 Prefetch Cache - $cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_prefetch_hit\") /max(\"l2_data_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_prefetch_hit\") /max(\"l2_meta_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "L1 Cache - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L1 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_data_read_hit\") /max(\"l1_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L1 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_meta_read_hit\") /max(\"l1_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L2 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "L2 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 76 },
   "options": {
    "content": "# L2 Cache\nLevel 2 cache is a back-end cache that caches file block that reside on that particular node."
   }
  },
  {
   "title": "L2 Prefetch Cache - $cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L3 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_prefetch_hit\") /max(\"l2_data_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L3 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_prefetch_hit\") /max(\"l2_meta_prefetch_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.cache",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_read_hit\") /max(\"l2_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "L2 Cache - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_read_hit\") /max(\"l2_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L2 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_read_hit\") /max(\"l2_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L3 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "L3 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 84 },
   "options": {
    "content": "# L3 Cache\nLevel 3 cache is an SSD backed cache that works with L2 Cache and contains blocks and metadata that are local to that particular node."
   }
  },
  {
   "title": "L3 Cache - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L3 Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l3_data_read_hit\") /max(\"l3_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "L3 Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l3_meta_read_hit\") /max(\"l3_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Disk IO for $cluster",
   "type": "timeseries",
   "description": "THis is a stacked graph so the total R+W is plotted for the overall B/W.  At the same time showing the contributions from each.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.disk.bytes.in.rate",
     "precision": "default",
     "query": "SELECT mean(\"value\") FROM \"cluster.disk.bytes.in.rate\" WHERE (\"cluster\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.disk.bytes.out.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "External Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.in.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.out.rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}